[package]
name = "r_pass"
version = "0.1.0"
edition = "2024"
description = "A program to quickly create a secure* password"
license = "GNU General Public License v3.0 or later"

[dependencies]
rand = "0.9.2"
sim_put = "0.1.1"
